import Head from "next/head";
import Script from "next/script";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      {/* <style jsx>
        {
          `
          .description1{
            color:red
          }
          `
        }
      </style> */}
      <Head>
        <title className="description1">Hunting Coder</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Welcome to Hunting Coder</h1>
        <p className={styles.description}>
          A Blog for hunting coders by a hunting coder
        </p>
        {/* ....blog..... */}
        <div className={styles.blogpost}>
          <h2 className={styles.subtitle}>Popular Blog Post</h2>
          <div>
            <h3>How to learn Javascrit in 2022</h3>
            <p>
              Lorem ipsum dolor, sit amet consectetur adipisicing elit. Eius,
              excepturi!
            </p>
          </div>
          <div>
            <h3>How to learn Javascrit in 2022</h3>
            <p>
              Lorem ipsum dolor, sit amet consectetur adipisicing elit. Eius,
              excepturi!
            </p>
          </div>
          <div>
            <h3>How to learn Javascrit in 2022</h3>
            <p>
              Lorem ipsum dolor, sit amet consectetur adipisicing elit. Eius,
              excepturi!
            </p>
          </div>
          <div>
            <h3>How to learn Javascrit in 2022</h3>
            <p>
              Lorem ipsum dolor, sit amet consectetur adipisicing elit. Eius,
              excepturi!
            </p>
          </div>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by <span className={styles.logo}></span>
        </a>
      </footer>
    </div>
  );
}
